# Generated by Django 4.2.2 on 2023-06-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_tweetmodel_usermodel_delete_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
